name: Deptry Dependency Check

on: [pull_request]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup the minimum required python distribution
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # Install deptry
      - run: pip install deptry
      # Remove testing related packages
      - run: deptry .
